main/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = "main"


urlpatterns = [
    path("index", views.index, name="Index_page"),
    path("authorization", views.authorization, name="log"),
    path("register", views.register, name="reg"),
    path("products/<int:id>", views.products, name="prod"),
    path("card/<int:id>", views.card, name="card"),
    path("cardsuc/<int:id>", views.cardsuc, name="cardsuc"),
    path("logout", views.logout_views, name="logout"),
    path("profile", views.prof, name="profile"),
    path("pay_cart<int:id>", views.pay_cart, name="pay_cart"),
    path("pay_cart_overall", views.pay_cart_overall, name="pay_cart_overall"),
    path("change_comment/<int:id>", views.change_comment, name="change_comment"),
    path("korzina", views.korzina, name="korzina"),
    path("add_cart/<int:id>", views.add_cart, name="add_cart"),
    path("delete_cart", views.delete_cart, name="delete_cart"),
    path("delete_comment/<int:id>", views.delete_comment, name="delete_comment"),
    path("change_password", views.change_password, name="change_password")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models


# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название продукт")
    descriptioon = models.TextField(verbose_name="Описание")
    cost = models.FloatField(verbose_name="Цена")
    available_amount = models.IntegerField(verbose_name="Есть в наличии")
    volume_type = models.ForeignKey("VolumeType", on_delete=models.SET_NULL, null=True)
    img = models.ImageField(upload_to="products", null=True)

    def __str__(self):
        return f"{self.name} - {self.descriptioon}"


class VolumeType(models.Model):
    name = models.CharField(max_length=30, verbose_name="Тип объема")

    def __str__(self):
        return f"{self.name}"


class Comment(models.Model):
    username = models.CharField(max_length=150, verbose_name="Имя пользователя")
    text = models.TextField(verbose_name="Коммент")
    img = models.ImageField(verbose_name="Картинка", null=True, blank=True)
    product = models.ForeignKey("Product", on_delete=models.CASCADE, verbose_name="Продукт")

    def __str__(self):
        return f"{self.username}: {self.text}"


class Card(models.Model):
    number = models.IntegerField(verbose_name="Номер карты")
    username = models.CharField(max_length=100, verbose_name="Имя на карточке")
    month = models.IntegerField(verbose_name="Месяц истечения времени", null=True)
    year = models.IntegerField(verbose_name="Год истечения времени", null=True)
    num = models.IntegerField(verbose_name="CVV2/CVC2", null=True)

    def __str__(self):
        return f"{self.number}"

main/forms.py
from django import forms
from .models import Comment
from .models import Card
from django.contrib.auth.models import User


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'username', 'text', 'product', 'img'
        ]


class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = [
            'number', 'username', 'month', 'year', 'num'
        ]


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username', 'password', 'email', 'first_name', 'last_name'
        ]

main/views.py
from django.shortcuts import render
from .models import Product
from .models import Comment
from .forms import CommentForm
from .forms import CardForm
from .models import Card
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User

from cloudipsp import Api, Checkout
from functools import reduce


api = Api(merchant_id=1396424, secret_key="test")
checkout = Checkout(api)

# Create your views here.
def index(request):
    products = Product.objects.all()
    return render(request, "main/Index.html", {"products": products})


def authorization(request):
    if request.user.is_authenticated:
        return render(request, "main/index.html", {})
    else:
        if request.method == "POST":
            username = request.POST["username"]
            password = request.POST["pass"]
            user = authenticate(username=username, password=password)

            if user != None:
                login(request, user)
                return redirect(reverse('main:Index_page'))
            else:
                return redirect(reverse('main:log'))
        return render(request, "main/authorization.html", {})


def register(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            username = request.POST["username"]
            password = request.POST["password"]
            email = request.POST["email"]
            first_name = request.POST["first_name"]
            last_name = request.POST["last_name"]

            user = User.objects.create_user(
                username=username,
                password=password,
                email=email,
                first_name=first_name,
                last_name=last_name
            )
            user.save()
            return redirect(reverse('main:log'))
        return render(request, "main/register.html", {})
    else:
        return render(request, "main/index.html", )



def prof(request):
    if request.user.is_authenticated:
        return render(request, "main/profile.html", {})
    else:
        return redirect(reverse("main:log"))


def products(request, id):
    product = Product.objects.get(pk=id)
    comments = Comment.objects.filter(product__pk=id)
    if request.method == "POST" and request.user.is_authenticated:
        username = request.user.username
        d = {"username": username,
             "text": request.POST["text"],
             "product": product
             }
        comment_form = CommentForm(d, request.FILES)
        if comment_form.is_valid():
            comment_form.save()
            return redirect(reverse('main:prod', args=(id,)))

    return render(request, "main/products.html", {"p": product, "comments": comments})


def card(request, id):
    prodcard = Product.objects.get(pk=id)
    if request.method == "POST":
        d = {
            "number": request.POST["number"],
            "username": request.POST["username"],
            "month": request.POST["month"],
            "year": request.POST["year"],
            "num": request.POST["num"]
        }

        card_form = CardForm(d, request.FILES)

        if card_form.is_valid():
            card_form.save()
            return redirect(reverse('main:cardsuc', args=(id,)))

    return render(request, "main/card.html", {"l": prodcard})


def cardsuc(request, id):
    cardsuc = Product.objects.get(pk=id)
    return render(request, "main/cardsuc.html", {"s": cardsuc})


def logout_views(request):
    logout(request)
    return redirect(reverse("main:Index_page"), {})


def pay_cart(request, id):
    product = Product.objects.get(pk=id)
    if request.user.is_authenticated:
        data = {"currency": "KZT", "amount": int(product.cost * 100)}
        url = checkout.url(data).get("checkout_url")
        return redirect(url)
    else:
        return redirect(reverse("main:log"))


def change_comment(request, id):
    comment = Comment.objects.get(pk=id)
    if request.user.is_authenticated:
        if request.method == "POST":
            text = request.POST["text"]
            comment.text = text
            comment.save()
            return redirect(reverse('main:Index_page', ))
        return render(request, "main/change_comment.html", {"g": comment})
    else:
        return redirect(reverse("main:log"))


def korzina(request):
    if request.user.is_authenticated:
        return render(request, "main/korzina.html", {})
    else:
        return redirect(reverse("main:log"))


def add_cart(request, id):
    cart = request.session.get("cart", [])
    cart.append(id)
    request.session["cart"] = cart
    return redirect(reverse("main:prod", args=(id,)))


def pay_cart_overall(request):
    if request.user.is_authenticated:
        cart = [Product.objects.get(pk=id) for id in request.session["cart"]]
        cost = reduce(lambda x, y: x + y, [c.cost for c in cart])
        data = {"currency": "KZT", "amount": int(cost * 100)}
        url = checkout.url(data).get("checkout_url")
        return redirect(url)
    else:
        return redirect(reverse("main:log"))


def delete_cart(request):
    request.session["cart"] = []
    return redirect(reverse("main:korzina"))


def delete_comment(request, id):
    if request.user.is_authenticated:
        Comment.objects.get(pk=id).delete()
        return redirect(reverse("main:Index_page"))


def change_password(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            password = request.POST["password"]
            user = request.user
            user.set_password(
                password
            )
            user.save()
            return redirect(reverse("main:profile"))
        return render(request, "main/change_password.html",)
    else:
        return redirect(reverse("main:log"))

main/templates/main/cardsuc.html
{% extends "main/Base.html" %}

{% block title %} ALABER {% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="header" style="margin-top: 10px;">
        <a href="{% url 'main:Index_page' %}" style="text-decoration: none;"><h3 style="margin-left: 300px; color: #5F5E5E;">ALABER</h3></a>
        <hr>
    </div>
</div>
<div class="container-fluid">
    <div class="row">

        <div class="window" style="margin-left: auto; margin-right: auto; background-color: #f8f9fa; width: 50%; margin-top: 30px; width: 45%">

            <div class="knopka">
                <button type="button" class="btn btn-light" style="width: 33%; background-color: #dc3545; color: white;">Банковская карта</button>
                <button type="button" class="btn btn-light" style="width: 33%; background-color: #dc3545; color: white;">Баланс мобильного</button>
                <button type="button" class="btn btn-light" style="width: 32%; background-color: #dc3545; color: white;">Электронные деньги</button>
                <hr>
            </div>

            <h5 style="margin-top: 10px; margin-left: 50px; color: #FFAD45; font-size: 2em;">Продукт: <span style="font-family: Comic Sans MS;">{{s.name}}</span></h5>

            <hr>
            <div class="into_window" style="width: 80%; margin-left: auto; margin-right: auto;">
                <h5 style="margin-top: 50px; margin-left: 50px; color: #7B8BA2" ><span style="font-family: Luminari, fantasy; font-size: 2em;">Покупка успешно совершена</span></h5>
                <h4  style="margin-left: 50px; color: #7B8BA2; font-family: Luminari, fantasy; font-size: 2em">Благодарим за  покупку!!!</h4>
            </div>
            <hr style="margin-top: 50px;">
            <div class="nomer" style="padding-bottom: 30px; margin-left: 20px; font-family: Luminari, fantasy;  color: #808080;">
                <span style="font-size: 1.3em;">Ваш номер  карточки:  </span>
            </div>
        </div>



    </div>
</div>


{% endblock %}

main/templates/main/korzina.html
{% extends "main/Base.html" %}
{% load tags %}
{% load static %}
{% block title %} ALABER {% endblock %}

{% block content %}
<div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12 fixed-top">
                <nav class="navbar navbar-expand-sm navbar-light bg-light">
                  <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'main:Index_page' %}">ALABER</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarColor03">
                      <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                          <a class="nav-link active" href="#">Бонусы
                          </a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">Избранные</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">Для вас</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">Популярные</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle show" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Категория</a>
                          <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Техника</a>
                            <a class="dropdown-item" href="#">Телефон и Аксессуары</a>
                            <a class="dropdown-item" href="#">Игрушки и спорт</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Музыка</a>
                          </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Скидки</a>
                        </li>
                        <li class="nav-item dropdown" style="margin-left: 70px;">
                            <a class="nav-link dropdown-toggle show" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Фильтр</a>
                            <div class="dropdown-menu">
                                <div class="lk" style="margin-left: 5px; color: #7F7F7F">
                                    <label class="form-label">От</label>
                                    <input type="number" class="form-control" placeholder="Цена от: " style="width: 95%;">
                                </div>
                                <div class="lk" style="margin-left: 5px; margin-top: 3px; color: #7F7F7F">
                                    <label class="form-label">До</label>
                                    <input type="number" class="form-control" placeholder="Цена от: " style="width: 95%;">
                                </div>

                                <div class="dropdown-divider"></div>

                            </div>
                        </li>
                      </ul>
                      <form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Поиск" style="width: 70%;">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit" style="margin-left: 2px;">Поиск</button>
                      </form>

                        {% if user.is_authenticated %}
                          <div class="right_header" style="margin-left: 1%;">
                            <ul class="navbar-nav me-auto">
                              <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle show" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Мой профиль</a>

                                <div class="dropdown-menu" style="width: 160%;">
                                    <div class="user" style="height: 80px;">
                                        <div class="row" style="height: 100%">

                                            <div class="userimg col-lg-4" style="width: 100%;">
                                                <img src="{% static 'main/img/user.png' %}" alt="user" style="padding-left: 2px; width:150%;">

                                            </div>
                                            <div class="userhello col-lg-8" style="width: 50%;">
                                                <span style="width: 100%">Здравствуйте {{request.user.first_name}}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="exit" style="width: 100%; float:right;">

                                        <a href="{% url 'main:logout' %}" style="color: black; text-decoration: none;"><button class="btn btn-warning pull-right" style="margin-left: 2px; margin-top: 2px;">Выход</button></a>
                                        <a href="{% url 'main:profile' %}" style="color: black; text-decoration: none;"><button class="btn btn-warning pull-right" style="margin-top: 2px;">Мой профиль</button></a>
                                        <hr>
                                    </div>

                                    <div style="margin-left: 11%;">Ваши деньги: 15000</div>
                                    <div style=" margin-top: 3px; margin-left: 11%;">Ваши монеты: 31</div>
                                    <a class="dropdown-item" href="#">История</a>
                                    <a class="dropdown-item" href="{% url 'main:korzina' %}">Корзина</a>
                                    <a class="dropdown-item" href="#">Мои купоны</a>
                                    <div class="dropdown-divider"></div>
                                </div>

                              </li>
                            </ul>
                          </div>
                        {% else %}
                            <div class="right_header" style="margin-left: 50px;">
                            <ul class="navbar-nav me-auto">
                              <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle show" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Мой профиль</a>

                                <div class="dropdown-menu" style="width: 165%;">
                                    <a href="{% url 'main:reg' %}" style="color: black; text-decoration: none;"><button type="submit" class="btn btn-warning pull-right" style="float:right; margin-right: 5%;">Регистрация</button></a>
                                    <a href="{% url 'main:log' %}" style="color: black; text-decoration: none;"><button type="submit" class="btn btn-warning pull-right" style="float:right; margin-right: 5%;">Вход</button></a>
                                </div>


                              </li>
                            </ul>
                          </div>
                        {% endif %}

                    </div>
                  </div>
                </nav>
            </div>
        </div>

</div>

<div class="container" style=" margin-top: 90px; margin-left: auto: margin-right: auto; width: 70%; font-family: Comic Sans MS, Comic Sans, cursive;">
    <div class="row">

            <div class="col-sm-8 col-xs-8" style="background-color: #E9E9E9; border-radius: 5px; border: solid 3px #dad7d5;">

                {% for id in request.session.cart %}
                    <div class="kor_prod" style="margin: 20px 0 20px 0; background-color: white;">
                        {% my_tag id as e %}
                        {% my_tag_img id as m %}
                        {% my_tag_cost id as c %}
                        <div class="row">
                            <div class="col-sm-3 col-lg-3" style="margin: 10px 0 10px 10px;">
                                <a href="{% url 'main:prod' id %} "><img src="{{MEDIA_URL}}{{m}}" alt="product"  style="border-radius: 5px; border: solid 5px #dad7d5; width: 100%;"></a>
                            </div>
                            <div class="col-sm-3 col-lg-3" style="color: #9122C1;">
                                <div class="kl" style="margin-top: 45%;">{{e}}</div>
                                <div class="opo">Цена: {{c}}</div>

                            </div>
                        </div>


                    </div>
                {% endfor %}

            </div>
            <div class="col-sm-4 col-xs-4" style="width:100%;">
                <img src="{% static 'main/img/korzina.png' %}" alt="korzina" style="width: 60%; margin-top: 20%;">
                <hr style="margin-top: 50%">
                <a href="{% url 'main:pay_cart_overall' %}"><button type="submit" class="btn btn-warning pull-right">Купить всё</button></a>
                <a href="{% url 'main:delete_cart' %}"><button type="submit" class="btn btn-warning pull-right">Удалить всё</button></a>
            </div>

    </div>
</div>


<div class="margin-8" style="margin-top: 8%;"></div>
<footer style="color: #666; background-color: #222; padding: 17px 0 18px 0; border-top: 1px solid #000;">
      <div class="container">
        <p class="text-center"><a href="{% url 'main:Index_page' %}" style="color: #999;">ALABER.KZ</a></p>
      </div>
</footer>


{% endblock %}

main/templates/main/profile.html
{% extends "main/Base.html" %}

{% load static %}
{% block title %} ALABER {% endblock %}

{% block content %}
<div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12 fixed-top">
                <nav class="navbar navbar-expand-sm navbar-light bg-light">
                  <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'main:Index_page' %}">ALABER</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarColor03">
                      <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                          <a class="nav-link active" href="#">Бонусы
                          </a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">Избранные</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">Для вас</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">Популярные</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle show" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Категория</a>
                          <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Техника</a>
                            <a class="dropdown-item" href="#">Телефон и Аксессуары</a>
                            <a class="dropdown-item" href="#">Игрушки и спорт</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Музыка</a>
                          </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Скидки</a>
                        </li>
                        <li class="nav-item dropdown" style="margin-left: 70px;">
                            <a class="nav-link dropdown-toggle show" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Фильтр</a>
                            <div class="dropdown-menu">
                                <div class="lk" style="margin-left: 5px; color: #7F7F7F">
                                    <label class="form-label">От</label>
                                    <input type="number" class="form-control" placeholder="Цена от: " style="width: 95%;">
                                </div>
                                <div class="lk" style="margin-left: 5px; margin-top: 3px; color: #7F7F7F">
                                    <label class="form-label">До</label>
                                    <input type="number" class="form-control" placeholder="Цена от: " style="width: 95%;">
                                </div>

                                <div class="dropdown-divider"></div>

                            </div>
                        </li>
                      </ul>
                      <form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Поиск" style="width: 70%;">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit" style="margin-left: 2px;">Поиск</button>
                      </form>

                        {% if user.is_authenticated %}
                          <div class="right_header" style="margin-left: 1%;">
                            <ul class="navbar-nav me-auto">
                              <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle show" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Мой профиль</a>

                                <div class="dropdown-menu" style="width: 160%;">
                                    <div class="user" style="height: 80px;">
                                        <div class="row" style="height: 100%">

                                            <div class="userimg col-lg-4" style="width: 100%;">
                                                <img src="{% static 'main/img/user.png' %}" alt="user" style="padding-left: 2px; width:150%;">

                                            </div>
                                            <div class="userhello col-lg-8" style="width: 50%;">
                                                <span style="width: 100%">Здравствуйте {{request.user.first_name}}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="exit" style="width: 100%; float:right;">

                                        <a href="{% url 'main:logout' %}" style="color: black; text-decoration: none;"><button class="btn btn-warning pull-right" style="margin-left: 2px; margin-top: 2px;">Выход</button></a>
                                        <a href="{% url 'main:profile' %}" style="color: black; text-decoration: none;"><button class="btn btn-warning pull-right" style="margin-top: 2px;">Мой профиль</button></a>
                                        <hr>
                                    </div>

                                    <div style="margin-left: 11%;">Ваши деньги: 15000</div>
                                    <div style=" margin-top: 3px; margin-left: 11%;">Ваши монеты: 31</div>
                                    <a class="dropdown-item" href="#">История</a>
                                    <a class="dropdown-item" href="{% url 'main:korzina' %}">Корзина</a>
                                    <a class="dropdown-item" href="#">Мои купоны</a>
                                    <div class="dropdown-divider"></div>
                                </div>

                              </li>
                            </ul>
                          </div>
                        {% else %}
                            <div class="right_header" style="margin-left: 50px;">
                            <ul class="navbar-nav me-auto">
                              <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle show" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Мой профиль</a>

                                <div class="dropdown-menu" style="width: 165%;">
                                    <a href="{% url 'main:reg' %}" style="color: black; text-decoration: none;"><button type="submit" class="btn btn-warning pull-right" style="float:right; margin-right: 5%;">Регистрация</button></a>
                                    <a href="{% url 'main:log' %}" style="color: black; text-decoration: none;"><button type="submit" class="btn btn-warning pull-right" style="float:right; margin-right: 5%;">Вход</button></a>
                                </div>


                              </li>
                            </ul>
                          </div>
                        {% endif %}

                    </div>
                  </div>
                </nav>
            </div>
        </div>

</div>

<div class="container" style="background-color: #E9E9E9; border-radius: 5px; border: solid 3px #dad7d5; margin-top: 90px; margin-left: auto: margin-right: auto; width: 60%; height: 500px; font-family: 'Poppins', sans-serif;">
    <div class="row">

            <div class="col-sm-4">
                <img src="{% static 'main/img/user2.png'%}" alt="user" style="width: 70%;">
            </div>
            <div class="col-sm-8" style="color: #787D7E;">
                <div class="info" style="margin-top: 20px;">
                    <span style="font-size: 1.3em;">Имя пользователя:</span> <span style="color: #E86E0F">{{request.user.first_name}}</span>
                    <hr>
                </div>
                 <div class="info" style="margin-top: 20px;">
                    <span style="font-size: 1.3em;">Фамилия:</span> <span style="color: #E86E0F">{{request.user.last_name}}</span>
                     <hr>
                </div>
                <div class="info" style="margin-top: 20px;">
                    <span style="font-size: 1.3em;">Логин:</span> <span style="color: #E86E0F">{{request.user.username}}</span>
                    <hr>
                </div>
                <div class="info" style="margin-top: 20px;">
                    <span style="font-size: 1.3em;">Email:</span> <span style="color: #E86E0F">{{request.user.email}}</span>
                    <hr>
                </div>
                <div class="info-pass " style="margin-top: 50px;">
                    <span style="font-size: 1.1em">Безопасность:</span>

                    <a href="{% url 'main:change_password' %}" ><button type="submit" name="password" class="btn btn-warning">Изменить пароль</button></a>

                </div>
                <div class="info-pass " style="margin-top: 20px;">
                    <span style="font-size: 1.1em">Добавить номер телефона:</span>
                    <input type="number" value="Добавить" class="btn" style="border-radius: 5px; border: solid 3px #dad7d5; background-color: white;">
                </div>
            </div>

    </div>
</div>


<div class="margin-8" style="margin-top: 8%;"></div>
<footer style="color: #666; background-color: #222; padding: 17px 0 18px 0; border-top: 1px solid #000;">
      <div class="container">
        <p class="text-center"><a href="{% url 'main:Index_page' %}" style="color: #999;">ALABER.KZ</a></p>
      </div>
</footer>


{% endblock %}